FROM node:18-alpine

# Crée un utilisateur sécurisé
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

# Dossier de travail
WORKDIR /app

# Copie les fichiers package.json
COPY package*.json ./

# Installation des dépendances
RUN npm ci

# Copie du reste du code
COPY . .

# Attribue les bons droits
RUN chown -R nextjs:nodejs /app

# Utilisateur non-root
USER nextjs

# Expose le port de l'app
EXPOSE 3000

# Démarrage de l'application
CMD ["npm", "run", "dev"]
